// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/songlun/Desktop/workspace/web/WuKongIMDocs/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
